import { ArrowRight, ArrowUpRight, Blocks, BriefcaseBusiness, Check, ChevronRight, CircleHelp, Compass, Gauge, Globe2, Layers3, Mail, Search, ShieldCheck, ShoppingBag, Sparkles, Workflow } from 'lucide-react';

const work = [
  { slug: 'dmf-luxury', name: 'DMF Luxury', sector: 'LUXURY COMMERCE', title: 'A premium commerce experience with a flexible editorial layer.', overview: 'A connected storefront combining Shopify commerce, a Next.js frontend and Sanity content management.', challenge: 'Bring product discovery and brand storytelling together in a premium storefront experience.', approach: 'Connected Shopify commerce with a headless Next.js storefront and Sanity CMS, with content and shopping journeys considered together.', services: 'Headless commerce · Frontend development · Content integration', tech: 'Shopify · Next.js · Sanity', features: ['Headless storefront architecture', 'Product and collection browsing', 'Editorial content managed in Sanity'], outcome: 'Delivered the described storefront and content setup. No verified post-launch performance metrics were provided for publication.', href: 'https://www.dmfluxury.com/pages/homepage', tone: 'ink' },
  { slug: 'world-of-reading', name: 'World of Reading', sector: 'SPECIALIST RETAIL · EDUCATION', title: 'A clearer way to navigate books, collections and learning resources.', overview: 'A Shopify commerce and content experience for a specialist bookseller serving readers and educators.', challenge: 'Help customers navigate a broad catalogue, specialist collections and language-based destinations.', approach: 'Worked across store navigation, collection structure, language hubs and reusable content experiences.', services: 'E-commerce · Information architecture · Content and SEO structure', tech: 'Shopify · Storefront content · Technical SEO', features: ['Structured collection discovery', 'Language-focused content hubs', 'Reusable page and content patterns'], outcome: 'Project scope included the described navigation and content structure. No verified conversion or revenue figures were supplied.', href: 'https://www.wor.com/', tone: 'paper' },
];

const serviceGroups = [
  { n: '01', title: 'Web & product development', icon: <Layers3/>, problem: 'A new digital product or business-critical website needs a dependable plan and delivery team.', work: 'Discovery, UX-aware engineering, responsive product builds, migrations and iterative releases.', fit: 'For teams launching a new service, replacing a dated platform or bringing an idea to market.', stack: 'Next.js · React · Angular · TypeScript' },
  { n: '02', title: 'Frontend development', icon: <Compass/>, problem: 'Your interface is hard to use, slow on mobile or difficult to extend.', work: 'Customer-facing interfaces, design-system implementation, accessibility improvements and frontend performance.', fit: 'For product teams improving key journeys or adding capacity to an existing engineering team.', stack: 'React · Next.js · Angular · JavaScript · TypeScript' },
  { n: '03', title: 'Backend, APIs & integrations', icon: <Workflow/>, problem: 'Important services, data and internal systems do not work together cleanly.', work: 'API design and implementation, business logic, third-party integrations, data flows and system handovers.', fit: 'For organizations connecting a website or product to the tools that run the business.', stack: 'Node.js · Express · Python · REST · GraphQL · PostgreSQL' },
  { n: '04', title: 'Full-stack applications', icon: <Blocks/>, problem: 'You need a complete product experience across interface, backend and data.', work: 'End-to-end web applications, customer portals, internal tools and MVPs with an agreed release scope.', fit: 'For teams that want one delivery partner to coordinate application layers.', stack: 'MERN · React · Node.js · PostgreSQL · APIs' },
  { n: '05', title: 'E-commerce & Shopify', icon: <ShoppingBag/>, problem: 'Your store needs a more capable storefront, catalogue experience or connected operation.', work: 'Shopify builds and improvements, theme work, headless storefronts, migrations, custom functions and integrations.', fit: 'For commerce teams improving shopping journeys, content workflows or platform flexibility.', stack: 'Shopify · Liquid · GraphQL · Storefront APIs · Functions' },
  { n: '06', title: 'WordPress & content platforms', icon: <BriefcaseBusiness/>, problem: 'Your team needs a website it can update without compromising structure or speed.', work: 'WordPress builds, theme and block development, CMS integrations, migrations and editor-friendly content models.', fit: 'For content-led organizations that need clear publishing workflows and maintainable pages.', stack: 'WordPress · PHP · REST APIs · Headless CMS' },
  { n: '07', title: 'AI & LLM integrations', icon: <Sparkles/>, problem: 'A useful AI workflow is possible, but its role, boundaries and data requirements are unclear.', work: 'LLM-powered search and assistance, model API integration, structured outputs and human review workflows.', fit: 'For teams testing a focused use case with clear data handling and success criteria.', stack: 'Python · Model APIs · Retrieval patterns · Application APIs' },
  { n: '08', title: 'Python automation & IoT', icon: <Gauge/>, problem: 'Manual operations or device workflows create repetitive work and fragmented information.', work: 'Python automation, data processing, device-to-cloud integrations and Azure IoT solution components.', fit: 'For organizations connecting operational systems, sensors or data-heavy workflows.', stack: 'Python · Azure · Azure IoT · APIs · PostgreSQL' },
  { n: '09', title: 'SEO, performance & ongoing care', icon: <Search/>, problem: 'Your website needs stronger technical foundations, clearer search structure or dependable follow-through.', work: 'Technical SEO, AEO/GEO content structure, site speed, Core Web Vitals work, integrations, support and maintenance.', fit: 'For teams protecting an investment, improving discoverability or planning continuous changes.', stack: 'Technical SEO · Structured data · Analytics · Performance audits' },
];

const technologyGroups = [
  { name: 'Frontend & product interfaces', technologies: 'React · Next.js · Angular · JavaScript · TypeScript', value: 'Build clear, responsive customer experiences and product interfaces that remain understandable as features grow.' },
  { name: 'Backend & application services', technologies: 'Node.js · Express · Python · MERN · REST APIs · GraphQL', value: 'Connect business logic, application data and third-party services so teams can reduce manual handoffs.' },
  { name: 'Commerce & content', technologies: 'Shopify · Liquid · GraphQL · Shopify Functions · WordPress · Sanity', value: 'Give commerce and content teams practical control over products, pages and customer-facing workflows.' },
  { name: 'Data, cloud & connected systems', technologies: 'PostgreSQL · Azure · Azure IoT · API integrations', value: 'Move information between systems and devices with an architecture matched to the actual operating context.' },
  { name: 'Search & experience quality', technologies: 'Technical SEO · AEO/GEO foundations · Core Web Vitals · Accessibility', value: 'Improve the way people and search systems discover, understand and use your digital experience.' },
];

const industries = [
  ['E-commerce & retail', 'Product discovery, merchandising, content-rich storefronts and connected operations.'],
  ['SaaS & technology', 'Marketing sites, customer portals, product interfaces and integrations.'],
  ['Education & publishing', 'Structured catalogues, language hubs, searchable resources and accessible content.'],
  ['Healthcare & IoT', 'Information experiences and connected workflows shaped around reliability and clear handoffs.'],
  ['Lifestyle & fashion', 'Brand-led digital experiences, product storytelling and commerce journeys.'],
  ['Professional services', 'Trust-building websites, useful service content, lead journeys and performance foundations.'],
];

const process = [
  ['01', 'Discovery', 'Understand your users, business goals, existing systems, constraints and measures of success.'],
  ['02', 'Strategy', 'Agree priorities, platform choices, scope, risks, responsibilities and a delivery roadmap.'],
  ['03', 'UX / UI', 'Shape page structure and interaction details around real customer tasks and content needs.'],
  ['04', 'Development', 'Build in reviewable increments, with clear decisions and working demonstrations.'],
  ['05', 'QA', 'Check key journeys, responsive behavior, content, accessibility basics and technical quality.'],
  ['06', 'Launch', 'Coordinate release readiness, handover, analytics and agreed launch support.'],
  ['07', 'Support', 'Plan ongoing fixes and improvements around your priorities and agreed service level.'],
];

const faqs = [
  ['Can you work with our existing website?', 'Yes. We can assess the current site, platform and integrations, then recommend improvements that preserve what is useful and address the main constraints.'],
  ['Do you work with international clients?', 'Yes. Remote collaboration is supported. Time-zone overlap, communication channels and review points are agreed during planning.'],
  ['Can you take over an existing codebase?', 'Yes. We start with a handover and technical review, document risks and dependencies, and propose a practical first set of priorities.'],
  ['Do you provide ongoing support?', 'Yes. Ongoing development, technical support and maintenance can be arranged with clear scope, capacity and response expectations.'],
  ['Which technologies do you work with?', 'Capabilities include React, Next.js, Angular, JavaScript and TypeScript, Node.js, Express, Python, MERN, Shopify, WordPress, PostgreSQL, Azure, APIs and technical SEO. We recommend the tools that fit your needs.'],
  ['How does a project start?', 'We begin with a conversation about goals, users, current systems and constraints. If there is a fit, we define the scope and provide a proposal with assumptions and milestones.'],
  ['How is pricing decided?', 'Pricing is scoped to the work, team mix, integrations, content and delivery needs. The proposal explains deliverables, exclusions, timing and commercial assumptions before you commit.'],
  ['Do you guarantee search rankings or AI citations?', 'No. Search rankings and AI-generated answers depend on factors outside any provider’s control. We can improve technical access, content clarity and structured information, then measure what is observable.'],
];

const Link = ({ href, children, className = '' }: {href:string;children:React.ReactNode;className?:string}) => <a href={href} className={className}>{children}</a>;
const Label = ({n,children}:{n:string;children:React.ReactNode}) => <div className="premium-label"><span>{n}</span>{children}</div>;
const CTA = ({title='Bring us the business problem.', text='Tell us what you want to build, improve or connect. We’ll help shape a clear next step.', light=false}:{title?:string;text?:string;light?:boolean}) => <section className={`premium-cta ${light?'light':''}`}><div><Label n="LET’S TALK">START A PROJECT CONVERSATION</Label><h2>{title}</h2><p>{text}</p></div><Link href="/contact" className="premium-button">Discuss your project <ArrowUpRight size={16}/></Link></section>;

export function AgencyLanding() {
  return <>
    <section className="premium-hero"><div className="premium-hero-copy"><p className="premium-kicker">DIGITAL ENGINEERING · COMMERCE · SEARCH · AUTOMATION</p><h1>Build what your<br/>business needs <em>next.</em></h1><p className="premium-lead">A senior-led digital engineering partner for organizations ready to improve customer experiences, connect systems and move important work forward.</p><div className="premium-actions"><Link href="/contact" className="premium-button">Talk through a project <ArrowUpRight size={16}/></Link><Link href="/work" className="premium-text-link">Explore selected work <ChevronRight size={16}/></Link></div><div className="premium-hero-note"><ShieldCheck size={18}/><span><b>Clear scope. Direct communication.</b><small>Delivery shaped around your business, team and existing systems.</small></span></div></div><div className="premium-hero-visual"><div className="hero-visual-top"><span>SELECTED DIGITAL WORK</span><span>01 / 02</span></div><a className="hero-project hero-project-dmf" href="/work/dmf-luxury"><div className="hero-project-image"><span>DMF</span><small>Luxury commerce<br/>experience</small></div><div className="hero-project-caption"><span><b>DMF Luxury</b><small>Commerce · Headless storefront</small></span><ArrowUpRight size={17}/></div></a><a className="hero-project hero-project-wor" href="/work/world-of-reading"><div className="hero-project-image"><span>WOR</span><small>Books for every<br/>curious mind</small></div><div className="hero-project-caption"><span><b>World of Reading</b><small>Commerce · Content experience</small></span><ArrowUpRight size={17}/></div></a><div className="hero-visual-index">STRATEGY <i/> ENGINEERING <i/> DELIVERY</div></div></section>

    <section className="premium-trust"><div className="premium-trust-intro"><small>SELECTED PROJECT EXPERIENCE</small><b>Work grounded in real delivery.</b></div><a href="/work/dmf-luxury">DMF Luxury <span>Commerce</span></a><a href="/work/world-of-reading">World of Reading <span>Retail · Education</span></a><div className="premium-trust-note"><Globe2 size={17}/><span>Remote collaboration<br/><b>India · Worldwide</b></span></div></section>

    <section className="premium-editorial"><Label n="01">THE PARTNERSHIP</Label><div className="premium-editorial-grid"><h2>Technology should make the next stage of your business <em>easier to reach.</em></h2><div><p>We help teams plan and deliver websites, commerce experiences, applications and integrations. You work directly with the people shaping the work, with decisions and priorities kept visible.</p><Link href="/about" className="premium-text-link">Meet the team and how we work <ArrowRight size={15}/></Link></div></div></section>

    <section className="premium-outcomes"><div className="premium-section-head"><Label n="02">BUSINESS OUTCOMES</Label><h2>Start with the change<br/>you need to make.</h2><p>Bring a customer or operational challenge. We’ll help turn it into a practical digital plan.</p></div><div className="premium-outcome-list">{[['Launch faster','Define a useful first release with the right scope, content and technology.','PRODUCT · WEB · COMMERCE'],['Improve conversion','Make key journeys clearer, easier to navigate and simpler to complete.','UX · STOREFRONT · PERFORMANCE'],['Automate manual operations','Connect data and reduce repeat work across everyday business processes.','PYTHON · APIS · WORKFLOWS'],['Modernize a legacy experience','Improve an older platform while managing migration and continuity.','MIGRATION · CMS · APPLICATIONS'],['Improve discoverability','Strengthen technical SEO, content structure and answer clarity.','SEO · AEO · GEO'],['Connect business systems','Bring storefronts, applications and internal tools into a more coherent flow.','INTEGRATIONS · DATA · CLOUD']].map(([title,body,tag],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div><small>{tag}</small></article>)}</div></section>

    <section className="premium-services"><div className="premium-section-head"><Label n="03">CAPABILITIES</Label><h2>Expertise across the<br/><em>digital delivery lifecycle.</em></h2><p>One partner across experience, application engineering, commerce and ongoing improvement.</p></div><div className="premium-service-list">{serviceGroups.slice(0,6).map(s=><a href="/services" key={s.n}><span>{s.n}</span><span className="service-list-icon">{s.icon}</span><span><b>{s.title}</b><small>{s.problem}</small></span><ArrowUpRight size={18}/></a>)}</div><Link href="/services" className="premium-text-link">Explore all services and delivery details <ArrowRight size={16}/></Link></section>

    <section className="premium-work"><div className="premium-section-head"><Label n="04">SELECTED PROJECTS</Label><h2>Real work, explained<br/>with <em>useful context.</em></h2><p>Read what each engagement covered, the challenge it addressed and what was delivered. We publish metrics only when they have been verified.</p></div><div className="premium-case-feature">{work.map((item,i)=><article key={item.slug} className={`premium-case ${item.tone}`}><div className="case-art-panel"><span className="case-counter">0{i+1} / CASE STUDY</span><span className="case-art-mark">{i===0?'DMF':'WOR'}</span><span className="case-art-strap">{item.sector}</span><div className="case-art-lines"/></div><div className="case-feature-copy"><span className="case-sector">{item.sector}</span><h3>{item.name}</h3><h4>{item.title}</h4><p>{item.overview}</p><div className="case-feature-meta"><span><small>DELIVERY</small>{item.services}</span><span><small>TECHNOLOGY</small>{item.tech}</span></div><Link href={`/work/${item.slug}`} className="premium-text-link">Read the case study <ArrowRight size={15}/></Link></div></article>)}</div></section>

    <section className="premium-tech"><div><Label n="05">TECHNOLOGY CAPABILITIES</Label><h2>The right tools<br/>for the work <em>ahead.</em></h2><p>We explain technology through what it helps your business and customers do. Stack choices follow product needs, existing systems, team skills and maintenance plans.</p><Link href="/technologies" className="premium-button premium-button-outline">Explore technology capabilities <ArrowUpRight size={15}/></Link></div><div className="premium-tech-list">{technologyGroups.slice(0,4).map((t,i)=><article key={t.name}><span>0{i+1}</span><div><h3>{t.name}</h3><b>{t.technologies}</b><p>{t.value}</p></div></article>)}</div></section>

    <section className="premium-industries"><div className="premium-section-head"><Label n="06">INDUSTRIES WE WORK WITH</Label><h2>We adapt to how<br/><em>your business operates.</em></h2><p>Industry context changes customer expectations, content structure and the systems a solution needs to fit.</p></div><div className="industry-editorial-list">{industries.map(([name,desc],i)=><article key={name}><span>0{i+1}</span><h3>{name}</h3><p>{desc}</p><ArrowUpRight size={16}/></article>)}</div></section>

    <section className="premium-why"><div><Label n="07">WHY CLIENTS CHOOSE US</Label><h2>Less uncertainty.<br/><em>Better delivery.</em></h2><p>Trust is earned through the way a team handles decisions, tradeoffs and follow-through.</p></div><div className="premium-why-list">{[['Direct developer communication','Discuss priorities with the people doing and guiding the work.'],['Architecture that can scale','Choose a foundation that fits today’s needs and leaves a sensible path forward.'],['Transparent delivery','Keep scope, progress, dependencies and decisions visible throughout the engagement.'],['Existing-system experience','Improve or extend your current platform where it makes sense.'],['Performance built in','Treat speed, accessibility and mobile usability as part of delivery quality.'],['Support after launch','Agree on handover, ownership and support before the release date.']].map(([t,d],i)=><article key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{d}</p></div><Check size={17}/></article>)}</div></section>

    <section className="premium-process"><div className="premium-section-head"><Label n="08">DELIVERY PROCESS</Label><h2>A visible path from<br/><em>first brief to launch.</em></h2><p>Seven steps create clear checkpoints. We tune the depth to the project while keeping ownership and decisions explicit.</p></div><div className="process-editorial">{process.map(([n,title,desc])=><article key={n}><span>{n}</span><div><h3>{title}</h3><p>{desc}</p></div></article>)}</div></section>

    <section className="premium-engagement"><div className="premium-section-head"><Label n="09">ENGAGEMENT MODELS</Label><h2>Choose the shape<br/>of the <em>partnership.</em></h2><p>Scope and commercial terms are written down before work starts.</p></div><div className="engagement-editorial">{[['Complete project','A defined outcome, delivery plan, milestones and agreed handover.'],['Dedicated developer','A consistent engineering resource working with your team and priorities.'],['Ongoing development','Planned capacity for a changing backlog, features and improvements.'],['Technical support & maintenance','Agreed support hours for fixes, updates, monitoring and technical care.']].map(([t,d],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p><Link href="/pricing">View scope options <ArrowRight size={14}/></Link></article>)}</div></section>

    <section className="premium-team"><div><Label n="10">ABOUT & TEAM</Label><h2>A small senior-led<br/><em>engineering team.</em></h2><p>Clients work directly with the people responsible for planning and delivery. We bring specialist support around the work when the scope needs it, without presenting a fictional roster of employees.</p><Link href="/about" className="premium-text-link">Read about the partnership <ArrowRight size={15}/></Link></div><div className="team-capability-roles">{[['01','Technical leadership','Architecture · estimation · engineering decisions'],['02','Product & experience','Discovery · information architecture · UX-aware delivery'],['03','Engineering delivery','Frontend · backend · commerce · integrations'],['04','Quality & growth','Testing · performance · SEO · ongoing improvement']].map(([n,t,d])=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>

    <section className="premium-honesty"><ShieldCheck size={22}/><div><Label n="CLIENT TRUST">NO INVENTED TESTIMONIALS OR METRICS</Label><p>Project references describe the work we can substantiate. We’ll add client quotes and measured outcomes when we have approval and verifiable evidence to share.</p></div></section>

    <section className="premium-faq"><div><Label n="11">FREQUENTLY ASKED</Label><h2>Questions worth<br/><em>answering early.</em></h2><p>Clear answers can make it easier to decide if the team and approach fit your project.</p><Link href="/faq" className="premium-text-link">All project FAQs <ArrowRight size={15}/></Link></div><div className="premium-accordion">{faqs.slice(0,5).map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
    <CTA title="A serious project deserves a clear start." text="Share the challenge, the systems involved and what success would mean to your team."/>
  </>;
}

export function AgencyServicesPage() {
  return <><section className="premium-page-hero"><Label n="SERVICES">DIGITAL ENGINEERING & GROWTH</Label><h1>Bring us the challenge.<br/><em>We’ll shape the delivery.</em></h1><p>From product development and e-commerce to search, automation and support, work with a team that can understand the business need and carry it into implementation.</p></section><section className="services-catalogue">{serviceGroups.map(s=><article key={s.n}><div className="catalogue-heading"><span>{s.n}</span>{s.icon}<h2>{s.title}</h2><small>{s.stack}</small></div><div className="catalogue-detail"><div><b>When clients come to us</b><p>{s.problem}</p></div><div><b>What we can deliver</b><p>{s.work}</p></div><div><b>Typical fit</b><p>{s.fit}</p></div></div><a href="/contact" className="premium-text-link">Discuss this capability <ArrowRight size={15}/></a></article>)}</section><CTA title="Not sure which service fits?" text="Describe the problem first. We can help identify the right mix of work after we understand the constraints."/></>;
}

export function AgencyWorkPage() {
  return <><section className="premium-page-hero"><Label n="SELECTED WORK">PROJECTS & PARTNERSHIPS</Label><h1>Different challenges.<br/><em>Carefully considered delivery.</em></h1><p>Explore the project context, client challenge, approach, services, technology, key features and known outcomes. No performance figures or testimonials are added without evidence.</p></section><section className="work-index">{work.map((item,i)=><article className={item.tone} key={item.slug}><div className="work-index-art"><span>0{i+1}</span><b>{item.name}</b><small>{item.sector}</small><div className="work-index-lines"/></div><div><span className="case-sector">{item.sector}</span><h2>{item.title}</h2><p>{item.overview}</p><p><b>Project focus</b><br/>{item.challenge}</p><Link href={`/work/${item.slug}`} className="premium-button premium-button-outline">Open case study <ArrowUpRight size={15}/></Link></div></article>)}</section><CTA/></>;
}

export function AgencyCaseStudyPage({slug}:{slug:string}) {
  const item=work.find(w=>w.slug===slug) || work[0];
  return <><section className={`premium-case-hero ${item.tone}`}><Label n="CASE STUDY">{item.sector}</Label><h1>{item.name}<br/><em>{item.title}</em></h1><p>{item.overview}</p><div className="case-hero-meta"><span><small>ENGAGEMENT</small>{item.services}</span><span><small>TECHNOLOGY</small>{item.tech}</span><a href={item.href} target="_blank" rel="noreferrer">Visit live website <ArrowUpRight size={15}/></a></div></section><section className="case-study-body"><div className="case-study-overview"><Label n="01">PROJECT OVERVIEW</Label><p>{item.overview}</p></div><article><span>02</span><div><h2>Client challenge</h2><p>{item.challenge}</p></div></article><article><span>03</span><div><h2>Approach & solution</h2><p>{item.approach}</p></div></article><article><span>04</span><div><h2>Services provided</h2><p>{item.services}</p></div></article><article><span>05</span><div><h2>Technology</h2><p>{item.tech}. Platform choices followed the implementation context and the required connection between commerce, content and customer experience.</p></div></article><article><span>06</span><div><h2>Key features</h2><ul>{item.features.map(f=><li key={f}><Check size={15}/>{f}</li>)}</ul></div></article><article className="case-result"><span>07</span><div><h2>Result & outcome</h2><p>{item.outcome}</p><small>We do not publish unverified business metrics or claims.</small></div></article></section><CTA title="Have a similar challenge?" text="We’ll start by understanding the customer journey, systems and project constraints behind it."/></>;
}

export function AgencyPricingPage(){
  const offers=[
    {name:'Digital presence & WordPress',price:'$750–$2,500',unit:'per project',forWho:'Company websites, redesigns and content-led sites, usually up to 8 core pages.',scope:'Page templates · content structure · responsive implementation · essential technical SEO.',basis:'Page count, content readiness, platform, custom design and migration needs.'},
    {name:'Web application & product',price:'$2,000–$8,000+',unit:'per project',forWho:'Customer portals, internal tools, MVPs and new product features.',scope:'Discovery · interface · frontend and backend delivery · integrations · QA and handover.',basis:'Feature scope, team mix, integrations, security and delivery risk.'},
    {name:'E-commerce & commerce systems',price:'$1,500–$5,000+',unit:'per project',forWho:'Shopify, headless commerce, store improvements, migration and catalogue work.',scope:'Storefront · product and content workflows · platform setup · integration planning · launch.',basis:'Catalogue complexity, custom behavior, migration, platform and connected systems.'},
    {name:'SEO & performance',price:'$350–$900',unit:'audit or focused project',forWho:'Technical SEO reviews, site performance improvements and search readiness.',scope:'Audit · prioritized fixes · page and schema structure · validation notes.',basis:'Site size, audit depth, implementation effort and analytics access.'},
    {name:'Automation, AI & IoT',price:'$850–$4,000+',unit:'per project · IoT from $1,500',forWho:'Python workflows, AI/LLM integrations, APIs and Azure IoT components.',scope:'Use-case definition · technical design · integration · guardrails · testing.',basis:'Data access, system dependencies, security requirements and operating environment.'},
    {name:'Ongoing engineering & care',price:'$400–$1,200 / month',unit:'monthly support · dedicated capacity from $2,200 / month',forWho:'Continuous development, technical support, maintenance or embedded developer capacity.',scope:'Agreed hours or capacity · shared backlog · response expectations · monthly review.',basis:'Capacity, availability, response targets, coverage and specialist requirements.'},
    {name:'SEO improvement retainer',price:'$500–$1,200 / month',unit:'monthly',forWho:'Ongoing technical SEO, content structure, performance and measurement improvements.',scope:'Agreed monthly priorities · implementation support · progress notes · review meeting.',basis:'Number of properties, implementation effort, content requirements and reporting needs.'},
  ];
  return <><section className="premium-page-hero"><Label n="PRICING CATALOGUE">GUIDE PRICES · USD</Label><h1>Know the likely investment<br/><em>before the first call.</em></h1><p>These planning ranges give you a realistic starting point across websites, products, commerce, search and engineering support. We confirm exact scope, deliverables and final pricing in writing before work begins.</p></section><section className="pricing-catalogue">{offers.map((offer,i)=><article key={offer.name}><span>0{i+1} / SCOPE OPTION</span><h2>{offer.name}</h2><div className="pricing-amount"><strong>{offer.price}</strong><small>{offer.unit}</small></div><p>{offer.forWho}</p><div><b>Common scope</b><p>{offer.scope}</p></div><div><b>What changes the price</b><p>{offer.basis}</p></div><a href="/contact" className="premium-text-link">Discuss this budget range <ArrowRight size={15}/></a></article>)}</section><section className="pricing-transparency"><CircleHelp size={21}/><div><h2>What’s included in the estimate?</h2><p>Your written proposal lists deliverables, milestones, assumptions, responsibilities and exclusions. Prices are in USD, exclude applicable taxes and third-party software or hosting, and are guide ranges rather than fixed quotes. Larger integrations, data migrations and content production are scoped separately.</p></div></section><CTA title="Have a budget in mind?" text="Share your target range and priorities. We can recommend a phase that fits the budget and makes the most useful progress."/></>;
}

export function AgencyTechnologyPage(){return <><section className="premium-page-hero"><Label n="TECHNOLOGY CAPABILITIES">A PRACTICAL, BUSINESS-LED STACK</Label><h1>Technology should solve<br/><em>the right problem.</em></h1><p>We select tools around your customers, current systems, delivery constraints and future maintenance needs. These capabilities support work we offer; the project determines the right combination.</p></section><section className="technology-catalogue">{technologyGroups.map((t,i)=><article key={t.name}><span>0{i+1}</span><div><h2>{t.name}</h2><b>{t.technologies}</b><p>{t.value}</p><small>Common work: {serviceGroups[Math.min(i,serviceGroups.length-1)].work}</small></div><ArrowUpRight size={18}/></article>)}</section><section className="technology-principles"><Label n="HOW WE CHOOSE">A RIGHT-FIT DECISION</Label><div>{[['Start with the user task','Choose a platform and architecture around the experience people need.'],['Respect the existing environment','Reuse systems and skills where they remain a good fit.'],['Plan for ownership','Consider who updates the site, supports integrations and maintains the code.'],['Explain tradeoffs','Make performance, flexibility, cost and complexity understandable.']].map(([h,p],i)=><article key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p></article>)}</div></section><CTA/></>}

export function AgencyFaqPage(){return <><section className="premium-page-hero"><Label n="FAQ">PROJECT QUESTIONS, ANSWERED</Label><h1>Know what to expect<br/><em>before kickoff.</em></h1><p>Clear, practical answers about scope, collaboration, technologies, pricing and ongoing support.</p></section><section className="faq-page-premium">{faqs.map(([q,a],i)=><details key={q}><summary><span>0{i+1}</span>{q}<b>+</b></summary><p>{a}</p></details>)}</section><CTA title="Still deciding what you need?" text="Share your question or project context. We can help you work out the most useful next step."/></>}

export function AgencyAboutPage(){return <><section className="premium-page-hero"><Label n="ABOUT ECOMMERCE SOLUTIONS">SMALL SENIOR-LED ENGINEERING TEAM</Label><h1>Close to the work.<br/><em>Accountable for delivery.</em></h1><p>We combine practical strategy, engineering and search expertise to help businesses build and improve useful digital experiences. Clients work directly with the people guiding and delivering the engagement.</p></section><section className="about-premium"><div><h2>Built around clear ownership.</h2><p>We keep the delivery team close to the decisions, communicate progress in plain language and surface constraints early. Where a project needs specialist skills, they are brought into an agreed delivery plan.</p></div><div>{[['Direct collaboration','Speak with the people responsible for your project, not a chain of account handoffs.'],['Careful recommendations','Understand the business need before choosing a platform or proposing a rebuild.'],['Transparent scope','See what is included, what depends on your team and how changes are handled.'],['Ownership after launch','Discuss content, code, access, documentation and support before handover.']].map(([h,p],i)=><article key={h}><span>0{i+1}</span><div><h3>{h}</h3><p>{p}</p></div></article>)}</div></section><section className="about-roles"><Label n="DELIVERY CAPABILITIES">THE PEOPLE AND SKILLS AROUND THE WORK</Label>{[['Technical leadership','Architecture · planning · technical decisions'],['Product & experience','Discovery · content structure · customer journeys'],['Engineering delivery','Frontend · backend · commerce · integrations'],['Quality & growth','Testing · performance · SEO · support']].map(([h,p],i)=><article key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p></article>)}</section><section className="premium-honesty"><ShieldCheck size={22}/><div><Label n="A NOTE ON PROOF">NO FICTIONAL TEAM BIOS OR TESTIMONIALS</Label><p>Team capability descriptions represent delivery roles, not named employees. Client endorsements and measured results will be published only with permission and evidence.</p></div></section><CTA/></>}

export function AgencySeoPage(){return <><section className="premium-page-hero"><Label n="SEO · AEO · GEO">SEARCH, ANSWERS & DISCOVERY</Label><h1>Be easier to find.<br/><em>And easier to understand.</em></h1><p>We improve the technical and content foundations that help visitors, search engines and answer systems understand your organization and services. No ranking or citation guarantees.</p></section><section className="seo-detail-grid">{[['Technical SEO','Crawl paths, indexability, metadata, canonical handling, internal links, mobile usability and site performance.'],['Answer engine readiness','Useful answers to real customer questions, with clear headings, structured explanations and relevant FAQs.'],['Generative search clarity','Consistent organization, service and case-study information, supported by accurate structured data.'],['Measurement & iteration','Prioritized recommendations based on your site, available analytics and business goals.']].map(([h,p],i)=><article key={h}><span>0{i+1}</span><h2>{h}</h2><p>{p}</p></article>)}</section><section className="seo-guardrail"><h2>What good SEO work can control.</h2><p>We can improve technical access, information clarity, page experience and implementation quality. Search positions, AI citations and business results depend on many other factors; we report the work completed and use available data to guide follow-up.</p></section><CTA title="Start with an honest review." text="We’ll look at your website, identify the clearest opportunities and explain what is practical to address."/></>}
